[build]
  # Build shared packages first, then web app
  command = "npm ci && npm run build --filter=@shared/types --filter=@shared/ui --filter=web"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9"

# Redirect API calls to your Azure backend
[[redirects]]
  from = "/api/*"
  to = "https://bandruption-api-hpfkc8azfyheb9a9.japaneast-01.azurewebsites.net/api/:splat"
  status = 200

# Handle client-side routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
