[build]
  # No base directory needed - we're building from root
  command = "npm run build --filter=web"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9"

# Redirect API calls to your Azure backend
[[redirects]]
  from = "/api/*"
  to = "https://your-server-domain.azurewebsites.net/api/:splat"
  status = 200

# Handle client-side routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Production environment variables (set in Netlify dashboard instead)
[context.production.environment]
  NODE_ENV = "production"
